[package]
name = "json_schemas"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde_json = { workspace = true }
serde_yaml = { version = "0.9" }

[dev-dependencies]
jsonschema = { workspace = true }
